# Generated by Django 2.1.7 on 2019-03-25 22:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, unique=True, verbose_name='Түскі үстел')),
            ],
            options={
                'verbose_name': 'Түскі үстел',
                'verbose_name_plural': 'Түскі үстел',
            },
        ),
        migrations.CreateModel(
            name='DeskOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='Тапсырыс')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Күні')),
                ('order_time', models.TimeField(blank=True, verbose_name='Уақыты')),
                ('client_name', models.CharField(default='', max_length=500, verbose_name='Аты-жөні')),
                ('mobile', models.IntegerField()),
                ('num_client', models.IntegerField(default=0)),
                ('table_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deskreserve.Desk')),
            ],
            options={
                'verbose_name': 'Тапсырыс',
                'verbose_name_plural': 'Тапсырыс',
            },
        ),
    ]
