# Generated by Django 2.1.7 on 2019-03-25 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskreserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskorder',
            name='order_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
