# Generated by Django 2.1.7 on 2019-03-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deskreserve', '0003_auto_20190326_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deskorder',
            name='desk',
        ),
        migrations.AddField(
            model_name='deskorder',
            name='desktop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deskreserve.Desk'),
            preserve_default=False,
        ),
    ]
