# Generated by Django 2.1.7 on 2019-03-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskreserve', '0005_auto_20190326_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskorder',
            name='name',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='Тапсырыс'),
        ),
    ]
