# Generated by Django 2.1.7 on 2019-03-25 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('table_id', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=6, primary_key=True, serialize=False, verbose_name='Table ID')),
                ('table_nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Table Name')),
                ('table_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Table Description')),
                ('table_occ_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Басталу уақыты')),
                ('table_occ_end', models.DateTimeField(default=datetime.datetime.now, verbose_name='Аяқталу уақыты')),
                ('table_is_available', models.BooleanField(default=True)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Tables',
                'verbose_name_plural': 'Tables',
            },
        ),
    ]
